### ISSUE TITLE
Service worker causes old version to be visible

### ISSUE THREAD

**Issue by helmuthb** [DACHFest/dachfest.com#40]

**Comment by mpoehler** [comment]
When the service-worker.js is updated, the website recognizes that and delivers these "new content available" snackbar. I see only two reasons why the service worker doesn't update: 

a) not re-created during build (travis has `skip_cleanup: true`)
b) firebase hosting or intermediate caches deliver an old version due to cache settings.

I also see lots of images from the blogs folder in the service-worker cache, that is something for another pull-request. Than we should see a fresh service worker file without these entries.

**Comment by emedvedev** [comment]
I've updated the service-worker cache settings in https://github.com/DACHFest/dachfest.com/commit/70e490b034b0b22e275557486cc830052fd89a93, although not completely sure it will help. Did update correctly for me though.

**Comment by mpoehler** [comment]
So, I added another Pull-Request #41, that removes the images from the blogs folder. 

Currently you see entries like this in the service-worker: 
`var precacheConfig = [[ .... "848d5c08096ca26378d57a076e0f3ef4"], ["images/posts/c4p.jpg", "1ee18a888f7d7c674f76ad5d8bb725f8"], ["images/posts/dfua17-announced.jpg", "4441fd2843db68aecfec597790c59a8d"], ["images/posts/lviv1.jpg", "4354a29ccf2baa79fef31ced66bb36dd"], ["images/posts/lviv2.jpg", "700946c36edbbedd93dd271382259d0a"], ["images/posts/lviv3.jpg", "4ce5e4d10037a9cab24382a1d39b7952"], ["images/posts/lviv4.jpg", "f68a1937b3bf5c258c32a53f38301d24"], ["images/posts/lviv5.jpg", "519bc22247ce396bc604989beef76a9d"], ["images/posts/lviv6.jpg", "c8439769ca4fb02750271fb25ef89b7c"], ["images/posts/lviv7.jpg", "fa948c45ebd3ea38d9e0a1fd75137051"], ["images/posts/lviv8.jpg", "c34f80c82735028eb943c4a2ea91e012"], ["images/posts/lviv9.jpg", "d4c0efd96029fa5d7ff043bc168fc556"], ["images/posts/summary16_1.jpg", "14d98367ed0d005c20bb9c7b9bc02e8d"], ["images/posts/summary16_2.jpg", "a47640a2994a0a73a59de55249fb82a6"], ["images/posts/summary16_3.jpg", "8012b53005ee95258655523b2b3d684b"], ["images/posts/summary16_4.jpg", "0874a236dd8afd9dd7a1ca4ef83e6078"], ["images/posts/summary16_5.jpg", "a5964c6d101e5f6aa95f84ed5dc724bf"], ["images/posts/summary16_6.jpg", "caed84fb2494c84fba212141fc94a594"], ["images/posts/summary16_7.jpg", "9af75d0743ab6f8ad2a3f8cc56a330b6"], ["images/posts/summary16_8.jpg", "5a8f700294aaab82ef11d54a7e7620de"], ["images/posts/thankyou_2.jpg", "f829204e63f31b7a23bd779cb633e119"], ["images/posts/thankyou_6.jpg", "4ef275f96f7418ea6d973f90e479eff8"], ["images/posts/thankyou_8.jpg", `

When merged, the new Version won't contain them anymore.

I'll try to check this with devtools closed.

**Comment by mpoehler** [comment]
@emedvedev I already see the fresh cache config.

**Comment by mpoehler** [comment]
The service-worker I got now look like this:

`var precacheConfig = [["data/accessibility.md", "34bced58f408940bed4aed73d3e488d0"], ["data/conduct.md", "9157acca0e17651ffd45e32d7d2ccdec"], ["data/dachfest-2018.json", "c10430c72c6c8fd9f0353e7fbadf0d29"], ["data/faq.md", "ca73ad18e0d5e667b0a878bd112f742b"], ["data/imprint.md", "e744e1e904dd207ae9691d1a4a7f8a57"], ["data/incident-handling.md", "532f3d576b849b41270d1b7c06cf82bf"], ["data/privacy.md", "4b14f8e4d8b1f66b5af44248a6d80aa6"], ["data/resources.json", "7e3559f1fb17cee56f38eb90d61c925f"], ["data/settings.json", "64aec332bc240be398e4efc786505a44"], ["data/violation-reporting.md", "928388b588f10a013bd27c1b214e2d39"], ["images/backgrounds/home.jpg", "745dd6377b1388484b612d4914bd3dee"], ["images/cover.jpg", "0f20b59529a872a85a4e2d427818ff3d"], ["images/favicon.ico", "c5272e5e38c6a48d334ccf9eb4485725"], ["images/link-icon.svg", "a74d433d19d03b4f4a84e57565087833"], ["images/logo-monochrome.svg", "32b910d249d6470feb049d2cead219d5"], ["images/logo.svg", "d5c400a1865a2b18b42ccbf69f3dc366"], ["images/logos/airbus.svg", "9579df4c90fcef043ad8049501613e77"], ["images/logos/flixbus.png", "e5b661366116d87796e48cf4b16f15e5"], ["images/logos/gdg-lviv.svg", "557e52d18aed88a36197d1388c67c985"], ["images/logos/gdg-x.svg", "f8fb99f2d34c78761130651f9d46c5ed"], ["images/logos/google.svg", "888b314b2d82dac34ba4f7d1df8e0a84"], ["images/logos/sotec.svg", "9114130e59195ca47bc99ea1eecfe9f6"], ["images/manifest/icon-144.png", "6660cd51632a8bfe545bba7fe30b1099"], ["images/manifest/icon-192.png", "a2e9356d0a6b79d5b08208fae4a04eb8"], ["images/manifest/icon-48.png", "319f370f637121710647ba5527dc026d"], ["images/manifest/icon-512.png", "8dae472662fc12663fb21d73daa206f3"], ["images/manifest/icon-72.png", "62442d0d0836f8842e958ee97c3c42f1"], ["images/manifest/icon-96.png", "5037cc743423231bc668d14cb4da7c0b"], ["images/map-marker.svg", "57c9e8c4e7715613012d1e1f94b82762"], ["images/organizer-logo.svg", "766e1c1661bed5e3b34c199beafddf81"], ["images/people/benjamin_stuermer.jpg", "0101051637dcb169e15cb22bc3037d18"], ["images/people/eduard_medvedev.jpg", "c84184e25b4a1f9e79cc5a2a833d7079"], ["images/people/madlaina_kalunder.jpg", "607e7476dcfe97a44a4cd8edd65e5b72"], ["images/people/raphael_miranda.jpg", "7464a752d0dbcdb91846a76cc15fe6a4"], ["images/people/timea_turdean.jpg", "848d5c08096ca26378d57a076e0f3ef4"], ["images/pretzels.jpg", "4d674fa7f96c0a54e1227eccd5ba56c7"], ["images/stroopwafels.jpg", "6bd6c2f330fa761245d2cca2aa7a583e"], ["index.html", "39bcd3645954aecb034357cfe85b1d97"], ["manifest.json", "d709e32c07fa287b3bf4af89a244d28f"], ["scripts/schedule-webworker.js", "351550fc1d6b8c4ada2112cdc8951488"], ["scripts/service-worker-registration.js", "d81b87a67f7840c7b44fd25d010f2319"], ["src/hoverboard-app.html", "a94ffbf40c6f8d8e8e65ca8f00bd381f"], ["src/lazy-resources.html", "e4e0baa0c8eece479eaf6b13ab2d9261"], ["src/pages/accessibility-page.html", "4f83c3a6ecb9f92e049de3643a0e14a9"], ["src/pages/blog-list-page.html", "b5b7f09383603e4030538edd5018e729"], ["src/pages/blog-page.html", "a7852b6e08e7fd6a43e735c1f6dd0af0"], ["src/pages/cod-page.html", "18c12c23d68a335fe6e3a677609f1db6"], ["src/pages/faq-page.html", "ad5be908244d253fb8e73deda8118e0f"], ["src/pages/home-page.html", "713dc1cb844580a8641f581f102ddfb7"], ["src/pages/imprint-page.html", "02a015d836777c3f25e1a2c40534c8c5"], ["src/pages/incident-handling-page.html", "2c24c10c82283341af6f70c0366e3309"], ["src/pages/post-page.html", "b7f83440cbfe419012fa824a2eb217d3"], ["src/pages/previous-speakers-page.html", "b74d22778958bef5ec03b1abe02f1b0a"], ["src/pages/privacy-page.html", "a71508ff5a43a75720587e28c7150776"], ["src/pages/schedule-page.html", "1404755f06b9568d90d6c02b9f7bcb9d"], ["src/pages/speakers-page.html", "670fb5b6e12324d4723d364bf1007d25"], ["src/pages/team-page.html", "28cae4f96cbbb6e3b48a824298c7debc"], ["src/pages/violation-reporting-page.html", "5e1c8540583fe676593e72337cba62eb"]]`

That shows, that delivering a new version of the service-worker works. 

@helmuthb can you confirm that you see the new version?

**Comment by emedvedev** [comment]
Same for me, I think the new cache settings worked.

**Comment by mpoehler** [comment]
**Bad news:** The cache header can't be the fix, because most browsers, including Chrome, ignore cache headers for service workers. ([See - Updating the service worker](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle)). The default cache settings in firebase hosting is max-age 3600, which means 1 hour. 

That can't be the reason for these ultra-old sites delivered in some browsers, like Anna using Chrome mentioned in Slack. 

My thoughts about that...

We have deployed a new service-worker.js yesterday and made sure that no caching is done. Browsers that already have a (probably old) service-worker installed, check on the next visit to an in-scope-page for an updated version of the service-worker ([See - Updating the service worker](https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle)). A service-worker is considered new when it is byte-different. That is the case for the one deployed yesterday. 

Also in the case that the Refesh-Snackbar was broken in an earlier version, at least two reloads (wait-> install) should update the service-worker. Or am I wrong?

What I also take into account is the prerender function. Its job is to create a prerendered version of the page for bots, but service-worker.js is a so called "Exact-match static content" and that has a higher priority than configured rewrites. The prerender function is not called for the service-worker.js, it is directly served by the hosting.

**Comment by helmuthb** [comment]
I think it is working now well. Thanks @mpoehler for the updates!
